# Mathematical Expression Errors (5 pts)
        program = Add(FloatingPointLiteral(1.0), IntLiteral(1))
        check_program_raises(InterpTypeError(), program)
        program = Add(IntLiteral(1), FloatingPointLiteral(1.0))
        check_program_raises(InterpTypeError(), program)
        program = Add(BooleanLiteral(True), BooleanLiteral(True))
        check_program_raises(InterpTypeError(), program)
        program = Add(Ren(), Ren())
        check_program_raises(InterpTypeError(), program)

        program = Subtract(FloatingPointLiteral(1.0), IntLiteral(1))
        check_program_raises(InterpTypeError(), program)
        program = Subtract(IntLiteral(1), FloatingPointLiteral(1.0))
        check_program_raises(InterpTypeError(), program)
        program = Subtract(BooleanLiteral(True), BooleanLiteral(True))
        check_program_raises(InterpTypeError(), program)
        program = Subtract(Ren(), Ren())
        check_program_raises(InterpTypeError(), program)

        program = Multiply(FloatingPointLiteral(1.0), IntLiteral(1))
        check_program_raises(InterpTypeError(), program)
        program = Multiply(IntLiteral(1), FloatingPointLiteral(1.0))
        check_program_raises(InterpTypeError(), program)
        program = Multiply(BooleanLiteral(True), BooleanLiteral(True))
        check_program_raises(InterpTypeError(), program)
        program = Multiply(Ren(), Ren())
        check_program_raises(InterpTypeError(), program)

        program = Divide(FloatingPointLiteral(1.0), IntLiteral(1))
        check_program_raises(InterpTypeError(), program)
        program = Divide(IntLiteral(1), FloatingPointLiteral(1.0))
        check_program_raises(InterpTypeError(), program)
        program = Divide(BooleanLiteral(True), BooleanLiteral(True))
        check_program_raises(InterpTypeError(), program)
        program = Divide(Ren(), Ren())
        check_program_raises(InterpTypeError(), program)

        program = Divide(IntLiteral(1), IntLiteral(0))
        check_program_raises(InterpMathError(), program)
        program = Divide(FloatingPointLiteral(1.0), FloatingPointLiteral(0.0))
        check_program_raises(InterpMathError(), program)

        # String concatenation (5 pts)
        program = Add(StringLiteral("Hello"), StringLiteral(", World"))
        check_run_result(("Hello, World", String(), None), run_stimpl(program))

        # String concatenation errors (5 pts)
        program = Subtract(StringLiteral("Hello"), StringLiteral(", World"))
        check_program_raises(InterpTypeError(), program)

        program = Multiply(StringLiteral("Hello"), StringLiteral(", World"))
        check_program_raises(InterpTypeError(), program)

        program = Divide(StringLiteral("Hello"), StringLiteral(", World"))
        check_program_raises(InterpTypeError(), program)